spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 202306
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  #配置redis相关信息
  redis:
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  mapper-locations: mapper/*.xml