spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/\u6CB3\u5357\u6D4B\u7ED8\u7BA1\u7406\u7CFB\u7EDF?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 202306
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  mapper-locations: mapper/*.xml