spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/河南测绘管理系统?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 202306
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  mapper-locations: mapper/*.xml